name: ax_responsive
description: A Flutter package for creating adaptive and responsive layouts across devices easily.
version: 0.0.6
repository: https://github.com/user97116/ax_responsive
issue_tracker: https://github.com/user97116/ax_responsive/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1 

flutter:
  plugin:
    platforms:
      android:
        default_package: ax_responsive
      ios:
        default_package: ax_responsive
      web:
        default_package: ax_responsive
      macos:
        default_package: ax_responsive
      windows:
        default_package: ax_responsive
      linux:
        default_package: ax_responsive
